_BASE_: [
  '/home/aistudio/PaddleDetection/configs/datasets/coco_detection.yml',
  '/home/aistudio/PaddleDetection/configs/runtime.yml',
  '/home/aistudio/PaddleDetection/configs/ppyoloe/_base_/optimizer_300e.yml',
  '/home/aistudio/PaddleDetection/configs/ppyoloe/_base_/ppyoloe_crn.yml',
  '/home/aistudio/PaddleDetection/configs/ppyoloe/_base_/ppyoloe_reader.yml',
]

log_iter: 100
snapshot_epoch: 10
weights: output/ppyoloe_crn_x_300e_coco/model_final

pretrain_weights: https://paddledet.bj.bcebos.com/models/pretrained/CSPResNetb_x_pretrained.pdparams
depth_mult: 1.33
width_mult: 1.25

TrainReader:
  batch_size: 14

LearningRate:
  base_lr: 0.0022
